import { getMigrationSqlFragments } from './migration-dialect';

describe('getMigrationSqlFragments', () => {
  it('returns SQLite-compatible identity, date, and boolean SQL', () => {
    expect(getMigrationSqlFragments('sqlite')).toEqual({
      generatedPrimaryKey: 'integer PRIMARY KEY AUTOINCREMENT NOT NULL',
      dateTimeType: 'datetime',
      booleanFalse: '0',
      largeIntegerType: 'bigint',
    });
  });

  it('returns Postgres-compatible identity, date, and boolean SQL', () => {
    expect(getMigrationSqlFragments('postgres')).toEqual({
      generatedPrimaryKey:
        'integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL',
      dateTimeType: 'timestamp',
      booleanFalse: 'FALSE',
      largeIntegerType: 'bigint',
    });
  });

  it('rejects database drivers unsupported by the migration set', () => {
    expect(() => getMigrationSqlFragments('mysql')).toThrow(
      'Unsupported migration database type: mysql',
    );
  });
});
