import type { DataSourceOptions } from 'typeorm';

export interface MigrationSqlFragments {
  generatedPrimaryKey: string;
  dateTimeType: string;
  booleanFalse: string;
  largeIntegerType: string;
}

/**
 * Resolves SQL fragments required by the migration set for a database driver.
 * @param type TypeORM database driver type.
 * @returns Portable fragments specialized for SQLite or Postgres.
 */
export function getMigrationSqlFragments(
  type: DataSourceOptions['type'],
): MigrationSqlFragments {
  if (type === 'sqlite') {
    return {
      generatedPrimaryKey: 'integer PRIMARY KEY AUTOINCREMENT NOT NULL',
      dateTimeType: 'datetime',
      booleanFalse: '0',
      largeIntegerType: 'bigint',
    };
  }

  if (type === 'postgres') {
    return {
      generatedPrimaryKey:
        'integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL',
      dateTimeType: 'timestamp',
      booleanFalse: 'FALSE',
      largeIntegerType: 'bigint',
    };
  }

  throw new Error(`Unsupported migration database type: ${type}`);
}
